version: '3.9'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - radazin_static_volume:/radazin/static
      - radazin_media_volume:/radazin/media
    networks:
      - nginx_network

volumes:
  radazin_static_volume:
    external: true
  radazin_media_volume:
    external: true
networks:
  nginx_network:
    external: true
